version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  pre_build:
    commands:
      - aws ssm get-parameter --region $AWS_REGION --name "$mongo_ssm_parameter" --with-decryption --output text --query Parameter.Value > .env
  build:
    commands:
      - echo Build started on `date`
      - SHORT=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c -6)
      - IMAGE_TAG=$(echo "$SHORT-$CODEBUILD_BUILD_NUMBER")
      - echo Build started on `date`
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker build --no-cache --build-arg account=${AWS_ACCOUNT_ID} -t $ECR_REPO:$IMAGE_TAG .
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo Build completed on `date`
      - aws eks update-kubeconfig --name $EKS_CLUSTER --region $AWS_REGION
      - envsubst < manifest/kube/dev/deployment.tmpl > manifest/kube/dev/deployment.yaml
      - kubectl apply -f manifest/kube/dev/deployment.yaml
